[package]
name = "create_new_latex_project"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
inquire = "0.7.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
